from .helper import *
from .PracticeUsage import *
from .InstituteTestUsage import *
from .SelfTestUsage import *
from .LearnUsage import *

api_mapping = {
    'text_analyze': text_analyze,
    'question_subset': question_subset,
    'question_accuracy': question_accuracy,
    'ksc': ksc,
    'videos': videos,
    'question_heatmap': question_heatmap,
    'question_heatmap_total': question_heatmap_total,
    'question_hist': question_hist,
    'login_count': login_count,
    'session_time': session_time ,
    'last_logged_in': last_logged_in,
    'practice_usage_session_time_range': practice_usage_session_time_range,
    'practice_usage_session_time_logscale': practice_usage_session_time_logscale,
    'course_wise_practice_usage_session': practice_usage_session_heatmap,
    'course_wise_practice_usage_session_time': practice_usage_session_time_heatmap,
    'course_wise_practice_usage_questions_used': practice_usage_questions_used_heatmap,
    'course_wise_practice_usage_unique_questions_used': practice_usage_unique_questions_used_heatmap,
    'course_wise_practice_usage_unique_users_heatmap': practice_usage_unique_users_heatmap,
    'course_wise_practice_usage_total_time_usage_heatmap': practice_usage_total_time_usage_heatmap,
    'course_wise_questions_per_practice_session_heatmap': questions_per_practice_session_heatmap,
    'course_wise_institute_test_per_user': institute_test_per_user_course,
    'course_wise_institute_test': institute_test_course,
    'course_wise_time_per_user': institute_test_time_per_user_course,
    'subject_wise_institute_test_per_user': institute_test_per_user_subject,
    'subject_wise_institute_test': institute_test_subject,
    'subject_wise_time_per_user': institute_test_time_per_user_subject,
    'institute_affiliation_analysis': institute_affiliation_analysis,
    'institute_daily_test_per_user': institute_daily_test_per_user,
    'daily_institute_test': daily_institute_test,
    'institute_daily_test_time_per_user': institute_daily_test_time_per_user,
    'institute_weekly_test_per_user': institute_weekly_test_per_user,
    'weekly_institute_test': weekly_institute_test,
    'institute_weekly_test_time_per_user': institute_weekly_test_time_per_user,
    'institute_monthly_test_per_user': institute_monthly_test_per_user,
    'monthly_institute_test': monthly_institute_test,
    'institute_monthly_test_time_per_user': institute_monthly_test_time_per_user,
    'institute_yearly_test_per_user': institute_yearly_test_per_user,
    'yearly_institute_test': yearly_institute_test,
    'institute_yearly_test_time_per_user': institute_yearly_test_time_per_user,
    'institute_quarterly_test_per_user': institute_quarterly_test_per_user,
    'quarterly_institute_test': quarterly_institute_test,
    'institute_quarterly_test_time_per_user': institute_quarterly_test_time_per_user,
    'course_wise_self_test_per_user': self_test_per_user_course,
    'course_wise_self_test': self_test_course,
    'course_wise_time_per_user': self_test_time_per_user_course,
    'subject_wise_self_test_per_user': self_test_per_user_subject,
    'subject_wise_self_test': self_test_subject,
    'subject_wise_time_per_user': self_test_time_per_user_subject,
    'self_affiliation_analysis': self_affiliation_analysis,
    'self_daily_test_per_user': self_daily_test_per_user,
    'daily_self_test': daily_self_test,
    'self_daily_test_time_per_user': self_daily_test_time_per_user,
    'self_weekly_test_per_user': self_weekly_test_per_user,
    'weekly_self_test': weekly_self_test,
    'self_weekly_test_time_per_user': self_weekly_test_time_per_user,
    'self_monthly_test_per_user': self_monthly_test_per_user,
    'monthly_self_test': monthly_self_test,
    'self_monthly_test_time_per_user': self_monthly_test_time_per_user,
    'self_yearly_test_per_user': self_yearly_test_per_user,
    'yearly_self_test': yearly_self_test,
    'self_yearly_test_time_per_user': self_yearly_test_time_per_user,
    'self_quarterly_test_per_user': self_quarterly_test_per_user,
    'quarterly_self_test': quarterly_self_test,
    'self_quarterly_test_time_per_user': self_quarterly_test_time_per_user,
    'course_wise_learn_test_per_user': learn_test_per_user_course,
    'course_wise_learn_test': learn_test_course,
    'course_wise_time_per_user': learn_test_time_per_user_course,
    'subject_wise_learn_test_per_user': learn_test_per_user_subject,
    'subject_wise_learn_test': learn_test_subject,
    'subject_wise_time_per_user': learn_test_time_per_user_subject,
    'learn_affiliation_analysis': learn_affiliation_analysis,
    'learn_daily_test_per_user': learn_daily_test_per_user,
    'daily_learn_test': daily_learn_test,
    'learn_daily_test_time_per_user': learn_daily_test_time_per_user,
    'learn_weekly_test_per_user': learn_weekly_test_per_user,
    'weekly_learn_test': weekly_learn_test,
    'learn_weekly_test_time_per_user': learn_weekly_test_time_per_user,
    'learn_monthly_test_per_user': learn_monthly_test_per_user,
    'monthly_learn_test': monthly_learn_test,
    'learn_monthly_test_time_per_user': learn_monthly_test_time_per_user,
    'learn_yearly_test_per_user': learn_yearly_test_per_user,
    'yearly_learn_test': yearly_learn_test,
    'learn_yearly_test_time_per_user': learn_yearly_test_time_per_user,
    'learn_quarterly_test_per_user': learn_quarterly_test_per_user,
    'quarterly_learn_test': quarterly_learn_test,
    'learn_quarterly_test_time_per_user': learn_quarterly_test_time_per_user,
}